version: 3

tasks:
  build:prod:
    cmds:
      - go build -ldflags "-w" -o ~/.local/bin/clock .

  build:dev:
    cmds:
      - go build -ldflags "-w" -o clock .

  test:
    cmds:
      - go run .
